# Generated by Django 3.2.23 on 2024-02-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20240205_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(default='x@x.com', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
    ]
