# Generated by Django 3.2.23 on 2024-02-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('reason', models.CharField(choices=[('general', 'General Enquiry'), ('order', 'Order Enquiry '), ('return', 'Return Request'), ('complaint', 'Complaint')], max_length=45)),
                ('message', models.TextField(max_length=800)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
