# Generated by Django 3.2.23 on 2024-02-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['id'], 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AddField(
            model_name='faq',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
