# Generated by Django 3.2.23 on 2024-02-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_auto_20240220_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='link',
            new_name='link_url',
        ),
        migrations.AddField(
            model_name='faq',
            name='link_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
